import json

with open('docs/presentation/slides.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for s in data['slides']:
    if s['id'] == 3:
        s['content_html'] = (
            "<div class='architecture-container'>"
            "<div class='arch-diagram'>"
            "<div class='arch-node node-client' id='arch-node-client'>"
            "<span class='node-tag'>Capa Superior</span>"
            "<div class='node-title'>UI (Flet) / Benchmarks / Suite de Tests</div>"
            "<div class='node-sub'>78 Tests Unitarios & Integración con 100% de Cobertura</div>"
            "</div>"
            "<div class='arch-connector-down' id='arch-connector-main'>⬇ Flujo de Consultas Unificado ⬇</div>"
            "<div class='arch-node node-gateway' id='arch-node-gateway'>"
            "<span class='node-tag'>Fachada Unificada (Patrón Facade)</span>"
            "<div class='node-title'>MotorInventario API</div>"
            "<div class='node-sub'>Intercambio dinámico de estrategia en tiempo de ejecución (Interruptor de Modo)</div>"
            "</div>"
            "<div class='arch-branches'>"
            "<div class='arch-branch branch-baseline' id='branch-baseline-card' tabindex='0' role='button' aria-label='Seleccionar ruta Baseline'>"
            "<div class='branch-header'>"
            "<span class='branch-badge red'>Línea Base (Baseline)</span>"
            "<h4>Implementación Ingenua O(n) / O(2^N)</h4>"
            "</div>"
            "<ul class='branch-specs'>"
            "<li><strong>Catálogo:</strong> <code>list[Producto]</code> en memoria contigua.</li>"
            "<li><strong>Búsqueda:</strong> Escaneo secuencial elemento a elemento O(n).</li>"
            "<li><strong>Top-N:</strong> Timsort completo de todo el universo con <code>sort()</code>.</li>"
            "<li><strong>Alternativas:</strong> Árbol de decisión recursivo puro sin memoria.</li>"
            "<li><strong>Caché:</strong> Inexistente (cada consulta recomputa desde cero).</li>"
            "</ul>"
            "<div class='branch-footer baseline-foot'>Clic para activar y simular flujo Baseline</div>"
            "</div>"
            "<div class='arch-branch branch-optimized active' id='branch-optimized-card' tabindex='0' role='button' aria-label='Seleccionar ruta Optimizada'>"
            "<div class='branch-header'>"
            "<span class='branch-badge green'>Modo Optimizado</span>"
            "<h4>Estructuras Avanzadas O(1) / O(N log k)</h4>"
            "</div>"
            "<ul class='branch-specs'>"
            "<li><strong>Catálogo:</strong> <code>dict[str, Producto]</code> hash indexado O(1).</li>"
            "<li><strong>Búsqueda:</strong> Hashing directo + índice invertido tokenizado.</li>"
            "<li><strong>Top-N:</strong> Min-Heap acotado con <code>heapq.nlargest</code> O(N log k).</li>"
            "<li><strong>Alternativas:</strong> Programación Dinámica memoizada O(N · P).</li>"
            "<li><strong>Caché:</strong> Caché LRU reactiva (128 slots) con invalidación atómica.</li>"
            "</ul>"
            "<div class='branch-footer opt-foot'>Clic para activar y simular flujo Optimizado (718x)</div>"
            "</div>"
            "</div>"
            "<div id='arch-flow-indicator' class='alert-box info mt-3' style='width: 100%; text-align: center; font-size: 13px;'>"
            "<strong>Estrategia Activa:</strong> Modo Optimizado habilitado — Las consultas resuelven en <code>dict</code> hash indexado en O(1)."
            "</div>"
            "</div>"
            "</div>"
        )
    elif s['id'] == 5:
        s['content_html'] = (
            "<div class='four-cards-grid'>"
            "<div class='struct-card' data-struct='list' tabindex='0' role='button' aria-label='Inspeccionar lista'>"
            "<div class='struct-header'><span class='icon'>📋</span><h4>list (Lista Contigua)</h4></div>"
            "<div class='struct-badge-complexity'>Búsqueda: O(n) | Acceso: O(1)</div>"
            "<p><strong>Uso en el Sistema:</strong> Línea base (Baseline) y orden cronológico de llegada de pedidos.</p>"
            "<div class='struct-visual list-vis'><span>[0]</span><span>[1]</span><span>[2]</span><span class='highlight-node'>[k]</span><span>...</span><span>[N]</span></div>"
            "<p class='tag-line'><strong>Trade-off:</strong> Máxima localidad espacial L1/L2, pero escaneo lineal O(n).</p>"
            "</div>"
            "<div class='struct-card highlight' data-struct='dict' tabindex='0' role='button' aria-label='Inspeccionar diccionario hash'>"
            "<div class='struct-header'><span class='icon'>⚡</span><h4>dict (Tabla Hash)</h4></div>"
            "<div class='struct-badge-complexity opt'>Búsqueda Promedio: O(1)</div>"
            "<p><strong>Uso en el Sistema:</strong> Catálogo maestro (ID ➔ Producto) e índices invertidos por tokens.</p>"
            "<div class='struct-visual hash-vis'><div class='hash-slot'>hash(k) ➔ Slot Directo en RAM</div></div>"
            "<p class='tag-line'><strong>Trade-off:</strong> Mayor consumo en RAM (+7.2 MB) a cambio de aceleración 260x.</p>"
            "</div>"
            "<div class='struct-card highlight' data-struct='heap' tabindex='0' role='button' aria-label='Inspeccionar min-heap'>"
            "<div class='struct-header'><span class='icon'>🌲</span><h4>heapq (Min-Heap)</h4></div>"
            "<div class='struct-badge-complexity opt'>Inserción / Extracción: O(log k)</div>"
            "<p><strong>Uso en el Sistema:</strong> Top-N de productos más demandados con memoria acotada O(k).</p>"
            "<div class='struct-visual heap-vis'><div class='heap-tree'>Raíz (Min) ➔ Hijos Izq/Der (Tamaño k)</div></div>"
            "<p class='tag-line'><strong>Trade-off:</strong> Memoria fija a k elementos en vez de duplicar y ordenar N.</p>"
            "</div>"
            "<div class='struct-card' data-struct='set' tabindex='0' role='button' aria-label='Inspeccionar conjunto set'>"
            "<div class='struct-header'><span class='icon'>🎯</span><h4>set (Conjuntos Hash)</h4></div>"
            "<div class='struct-badge-complexity'>Pertenencia: O(1)</div>"
            "<p><strong>Uso en el Sistema:</strong> Integridad referencial instantánea e intersección en búsqueda rápida.</p>"
            "<div class='struct-visual set-vis'><span>A ∩ B = { Tokens Coincidentes }</span></div>"
            "<p class='tag-line'><strong>Trade-off:</strong> Unicidad matemática garantizada sin recorrer listas.</p>"
            "</div>"
            "</div>"
            "<div id='struct-detail-box' class='alert-box info mt-3'>"
            "💡 <strong>Auditoría Interactiva:</strong> Haz clic en cualquiera de las 4 tarjetas de estructuras para inspeccionar su disposición en memoria física y su trade-off algorítmico."
            "</div>"
        )
    elif s['id'] == 6:
        s['content_html'] = (
            "<div class='two-col'>"
            "<div class='panel highlight'>"
            "<div class='panel-header-with-badge'><h3>Memoización (Nivel Algorítmico)</h3><span class='badge success'>Interno DP</span></div>"
            "<p class='subtitle-panel'>Módulo: <code>src/pedidos/combinaciones.py</code></p>"
            "<ul class='bullet-list'>"
            "<li><strong>Qué almacena:</strong> Subproblemas evaluados: <code>(indice_candidato, presupuesto_restante)</code>.</li>"
            "<li><strong>Por qué conviene:</strong> Distintas ramas del árbol recursivo coinciden en el mismo remanente de presupuesto.</li>"
            "<li><strong>Ciclo de Vida:</strong> Efímero durante una sola consulta combinatoria (DP acotada).</li>"
            "<li><strong>Impacto:</strong> Reduce la complejidad de O(2^N) a O(N · P), resolviendo en <strong>< 1 ms</strong> lo que en modo recursivo puro tardaba minutos.</li>"
            "</ul>"
            "<div class='tree-demo-box mt-3'>"
            "<div class='tree-label'>Árbol de Decisión:</div>"
            "<div class='tree-nodes'><span class='node-normal'>f(0, p=1000)</span> ➔ <span class='node-branch'>f(1, p=600)</span> ➔ <span class='node-memo'>⚡ Memo Hit: Retorno O(1)</span></div>"
            "</div>"
            "</div>"
            "<div class='panel'>"
            "<div class='panel-header-with-badge'><h3>Caching Inteligente (Nivel Sistema)</h3><span class='badge primary'>Global LRU</span></div>"
            "<p class='subtitle-panel'>Módulo: <code>src/cache/cache_consultas.py</code></p>"
            "<ul class='bullet-list'>"
            "<li><strong>Qué almacena:</strong> Consultas frecuentes del usuario (búsqueda por texto y ranking Top-N).</li>"
            "<li><strong>Política de Desalojo:</strong> Capacidad acotada a 128 entradas con política <em>Least Recently Used</em> (LRU).</li>"
            "<li><strong>Consistencia Reactiva:</strong> Para evitar datos obsoletos (<em>stale reads</em>), el motor purga automáticamente:</li>"
            "</ul>"
            "<div class='cache-interactive-widget mt-3'>"
            "<div class='cache-slot-row' id='cache-slots-display'>"
            "<span class='cache-slot-item hit' id='slot-1'>Slot 1: \"laptop\" [Hit]</span>"
            "<span class='cache-slot-item hit' id='slot-2'>Slot 2: \"mouse\" [Hit]</span>"
            "<span class='cache-slot-item lru' id='slot-3'>Slot 3: LRU Evict</span>"
            "</div>"
            "<div class='cache-actions-row mt-3' style='display: flex; gap: 8px; flex-wrap: wrap;'>"
            "<button type='button' class='btn' id='btn-cache-demo-hit' style='font-size: 12px; padding: 6px 10px;'>Consultar \"laptop\" (Hit 0.01ms)</button>"
            "<button type='button' class='btn' id='btn-cache-demo-miss' style='font-size: 12px; padding: 6px 10px;'>Consultar \"teclado\" (Miss ➔ Carga)</button>"
            "<button type='button' class='btn' id='btn-cache-demo-invalidate' style='font-size: 12px; padding: 6px 10px; color: var(--stamp-crimson);'>Mutar Stock (Invalidar Caché)</button>"
            "</div>"
            "<div id='cache-feedback' class='mt-3' style='font-size: 12.5px; font-family: var(--font-mono); color: var(--ink-secondary); background: var(--bg-sheet-muted); border: 1px solid var(--border-paper); padding: 8px 12px; border-radius: var(--radius-xs);'>"
            "Estado: Caché sincronizada con el catálogo. Presiona un botón para probar consistencia."
            "</div>"
            "</div>"
            "</div>"
            "</div>"
        )
    elif s['id'] == 7:
        s['content_html'] = (
            "<div class='two-col'>"
            "<div class='panel'>"
            "<h3>Implementación Multiproceso</h3>"
            "<p>La preparación de un lote de 2.000 pedidos es una tarea conceptualmente paralelizable (cada pedido se valida de forma independiente):</p>"
            "<ul class='bullet-list'>"
            "<li><strong>Mecanismo:</strong> <code>concurrent.futures.ProcessPoolExecutor</code> distribuyendo bloques (chunks) de pedidos entre los núcleos de la CPU.</li>"
            "<li><strong>Evasión del GIL:</strong> Al utilizar procesos independientes (y no hilos de <code>threading</code>), se aprovecha el 100% de la potencia multinúcleo en tareas CPU-bound.</li>"
            "<li><strong>Determinismo:</strong> El catálogo se comparte en modo de solo lectura durante la simulación de despacho.</li>"
            "</ul>"
            "</div>"
            "<div class='panel highlight'>"
            "<h3>Lección Empírica: Sobrecarga de IPC en Windows</h3>"
            "<div class='alert-box info'><strong>Medición Experimental (Dataset Grande - 10.000 prod, 2.000 ped):</strong><br>Mono-hilo (Hash O(1)): <strong>29.80 ms</strong> | Concurrente (ProcessPool): <strong>848.12 ms</strong></div>"
            "<div class='ipc-breakdown-chart'>"
            "<div class='ipc-bar-title'>Desglose del Tiempo Concurrente (848 ms) — Haz clic en los segmentos:</div>"
            "<div class='ipc-bar-stack'>"
            "<button type='button' class='ipc-seg seg-spawn' data-ipc='spawn' style='width: 25%; border: none;' title='Creación de Procesos (Spawn en Windows): ~210 ms'>Spawn 25%</button>"
            "<button type='button' class='ipc-seg seg-pickle' data-ipc='pickle' style='width: 38%; border: none;' title='Serialización Pickle de 10.000 objetos: ~320 ms'>Pickle 38%</button>"
            "<button type='button' class='ipc-seg seg-pipe' data-ipc='pipe' style='width: 32%; border: none;' title='Transferencia por Pipes IPC: ~270 ms'>Pipes 32%</button>"
            "<button type='button' class='ipc-seg seg-calc' data-ipc='calc' style='width: 5%; border: none;' title='Cómputo Real en RAM: ~48 ms'>CPU 5%</button>"
            "</div>"
            "<div id='ipc-detail-box' class='mt-3' style='background: var(--bg-sheet); border: 1px solid var(--border-paper); border-radius: var(--radius-xs); padding: 10px 14px; font-size: 12.5px; color: var(--ink-secondary);'>"
            "<strong>Auditoría de Sobrecarga:</strong> Haz clic en cualquiera de los bloques de color para analizar por qué la coordinación entre procesos costó 28 veces más que el cálculo en memoria."
            "</div>"
            "</div>"
            "<p class='footnote mt-3'><strong>Conclusión Fundamental:</strong> El paralelismo solo es ventajoso si el costo de cálculo por ítem supera con creces el costo fijo de sincronización y transferencia de memoria.</p>"
            "</div>"
            "</div>"
        )
    elif s['id'] == 11:
        s['content_html'] = (
            "<div class='three-col'>"
            "<div class='panel highlight'><div class='conclusion-header'><span class='conclusion-icon'>🏆</span><h3>Mayor Impacto</h3></div><ul class='bullet-list'><li><strong>Programación Dinámica:</strong> Evitó el colapso exponencial O(2^N) pasando de minutos incomputables a <strong>< 1 ms</strong> en combinaciones sustitutas.</li><li><strong>Catálogo Hash:</strong> Redujo la búsqueda de pedidos de O(P · L · n) a O(P · L), generando una aceleración de <strong>27x a 260x</strong>.</li></ul></div>"
            "<div class='panel'><div class='conclusion-header'><span class='conclusion-icon'>⚠️</span><h3>Decisión Subóptima</h3></div><ul class='bullet-list'><li><strong>Paralelismo Multiproceso:</strong> Para operaciones O(1) en RAM, la serialización <code>pickle</code> e IPC en Windows anuló cualquier ventaja multinúcleo.</li><li>La optimización mono-hilo fue <strong>28 veces más rápida</strong> que el clúster multiproceso.</li></ul></div>"
            "<div class='panel'><div class='conclusion-header'><span class='conclusion-icon'>🚀</span><h3>¿Qué Haríamos Diferente?</h3></div><ul class='bullet-list'><li><strong>Memoria Compartida:</strong> Emplear <code>multiprocessing.shared_memory</code> o buffers contiguos de NumPy.</li><li><strong>Extensiones Nativas:</strong> Implementar los bucles críticos en Cython/Rust para exprimir la CPU.</li><li><strong>Persistencia Indexada:</strong> SQLite en memoria con índices B-Tree para queries multivariable.</li></ul></div>"
            "</div>"
            "<div class='mt-3' style='text-align: center;'>"
            "<button type='button' class='btn btn-primary btn-pack-slide' id='btn-pack-from-slide' style='font-size: 13.5px; padding: 10px 22px; gap: 8px;'>"
            "<span>📦 Empaquetar y Despachar Presentación</span>"
            "</button>"
            "</div>"
        )

with open('docs/presentation/slides.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Updated slides.json successfully!")
